// ============================================================
// DFP UAT Agent — Database Types
// ============================================================
// Generated by: supabase gen types typescript --local
//
// ⚠️  THIS IS A PLACEHOLDER. Run the following command to generate
//    the real types after Supabase migrations are applied:
//
//    supabase gen types typescript --local > src/lib/supabase/database.types.ts
//
// ============================================================

export interface Database {
  public: {
    Tables: {
      uat_projects: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          approved_base_urls: string[];
          environment: 'demo' | 'uat' | 'staging' | 'production';
          enabled: boolean;
          default_safety_policy: Record<string, unknown> | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          approved_base_urls?: string[];
          environment?: 'demo' | 'uat' | 'staging' | 'production';
          enabled?: boolean;
          default_safety_policy?: Record<string, unknown> | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          approved_base_urls?: string[];
          environment?: 'demo' | 'uat' | 'staging' | 'production';
          enabled?: boolean;
          default_safety_policy?: Record<string, unknown> | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      uat_test_plans: {
        Row: {
          id: string;
          project_id: string;
          name: string;
          description: string | null;
          test_mode: 'smoke' | 'journey' | 'full_uat' | 'release_comparison';
          stop_on_critical: boolean;
          retry_count: number;
          retry_delay_ms: number;
          enabled: boolean;
          notification_rules: Record<string, unknown> | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          name: string;
          description?: string | null;
          test_mode?: 'smoke' | 'journey' | 'full_uat' | 'release_comparison';
          stop_on_critical?: boolean;
          retry_count?: number;
          retry_delay_ms?: number;
          enabled?: boolean;
          notification_rules?: Record<string, unknown> | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          name?: string;
          description?: string | null;
          test_mode?: 'smoke' | 'journey' | 'full_uat' | 'release_comparison';
          stop_on_critical?: boolean;
          retry_count?: number;
          retry_delay_ms?: number;
          enabled?: boolean;
          notification_rules?: Record<string, unknown> | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      uat_test_journeys: {
        Row: {
          id: string;
          plan_id: string;
          name: string;
          description: string | null;
          test_role_ref: string | null;
          execution_order: number;
          enabled: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          plan_id: string;
          name: string;
          description?: string | null;
          test_role_ref?: string | null;
          execution_order?: number;
          enabled?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          plan_id?: string;
          name?: string;
          description?: string | null;
          test_role_ref?: string | null;
          execution_order?: number;
          enabled?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      uat_journey_steps: {
        Row: {
          id: string;
          journey_id: string;
          step_order: number;
          step_type: string;
          name: string;
          selector_strategy: string | null;
          selector_value: string | null;
          input_value_ref: string | null;
          expected_result: string | null;
          timeout_ms: number;
          retry_count: number;
          required: boolean;
          mask_value: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          journey_id: string;
          step_order: number;
          step_type: string;
          name: string;
          selector_strategy?: string | null;
          selector_value?: string | null;
          input_value_ref?: string | null;
          expected_result?: string | null;
          timeout_ms?: number;
          retry_count?: number;
          required?: boolean;
          mask_value?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          journey_id?: string;
          step_order?: number;
          step_type?: string;
          name?: string;
          selector_strategy?: string | null;
          selector_value?: string | null;
          input_value_ref?: string | null;
          expected_result?: string | null;
          timeout_ms?: number;
          retry_count?: number;
          required?: boolean;
          mask_value?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      uat_test_runs: {
        Row: {
          id: string;
          project_id: string;
          plan_id: string | null;
          triggered_by: string | null;
          environment: string;
          build_reference: string | null;
          status: string;
          test_mode: string | null;
          browsers: string[];
          viewports: string[];
          safety_snapshot: Record<string, unknown> | null;
          start_time: string | null;
          end_time: string | null;
          duration_ms: number;
          current_journey_id: string | null;
          current_step_id: string | null;
          progress: number;
          total_steps: number;
          passed_count: number;
          failed_count: number;
          warning_count: number;
          blocked_count: number;
          pass_rate: number;
          bugs_found: number;
          readiness_score: number | null;
          n8n_execution_ref: string | null;
          browser_worker_ref: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          plan_id?: string | null;
          triggered_by?: string | null;
          environment?: string;
          build_reference?: string | null;
          status?: string;
          test_mode?: string | null;
          browsers?: string[];
          viewports?: string[];
          safety_snapshot?: Record<string, unknown> | null;
          start_time?: string | null;
          end_time?: string | null;
          duration_ms?: number;
          current_journey_id?: string | null;
          current_step_id?: string | null;
          progress?: number;
          total_steps?: number;
          passed_count?: number;
          failed_count?: number;
          warning_count?: number;
          blocked_count?: number;
          pass_rate?: number;
          bugs_found?: number;
          readiness_score?: number | null;
          n8n_execution_ref?: string | null;
          browser_worker_ref?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          plan_id?: string | null;
          triggered_by?: string | null;
          environment?: string;
          build_reference?: string | null;
          status?: string;
          test_mode?: string | null;
          browsers?: string[];
          viewports?: string[];
          safety_snapshot?: Record<string, unknown> | null;
          start_time?: string | null;
          end_time?: string | null;
          duration_ms?: number;
          current_journey_id?: string | null;
          current_step_id?: string | null;
          progress?: number;
          total_steps?: number;
          passed_count?: number;
          failed_count?: number;
          warning_count?: number;
          blocked_count?: number;
          pass_rate?: number;
          bugs_found?: number;
          readiness_score?: number | null;
          n8n_execution_ref?: string | null;
          browser_worker_ref?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      // Additional table types (journey_results, agent_findings, bug_reports, etc.)
      // will be fully generated by: supabase gen types typescript --local
    };
    Functions: {
      is_staff_user: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      is_staff_admin: {
        Args: Record<string, never>;
        Returns: boolean;
      };
    };
  };
}

// Re-export commonly used table row types
export type UatProjectRow = Database['public']['Tables']['uat_projects']['Row'];
export type UatTestPlanRow = Database['public']['Tables']['uat_test_plans']['Row'];
export type UatTestJourneyRow = Database['public']['Tables']['uat_test_journeys']['Row'];
export type UatJourneyStepRow = Database['public']['Tables']['uat_journey_steps']['Row'];
export type UatTestRunRow = Database['public']['Tables']['uat_test_runs']['Row'];